# Generated by Django 2.1 on 2018-08-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ACTIVITY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Who_has_paid', models.CharField(max_length=250)),
                ('Amount_person_has_paid', models.IntegerField()),
                ('Items_on_which_spent', models.CharField(max_length=250)),
                ('Split_between_number_of_people', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PEOPLE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_are_you_with', models.CharField(max_length=500)),
            ],
        ),
    ]
