# Generated by Django 2.1 on 2018-08-11 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SPLITWISE', '0002_auto_20180811_2039'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PERSONS',
            new_name='PEOPLE',
        ),
    ]
